[workspace]
authors = ["tdgfrost <100413067+tdgfrost@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "DecisionDiscretisationOfflineRL"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.11"

[pypi-dependencies]
tqdm = ">=4.67.1, <5"
matplotlib = ">=3.10.5, <4"
torch = ">=2.6.0, <3"
setuptools = ">=80.9.0, <81"
click = ">=8.2.1, <9"
requests = ">=2.32.5, <3"
stable-baselines3 = ">=2.7.0, <3"
polars = ">=1.33.0, <2"
gymnasium = "<1.0"
minigrid = ">=3.0.0, <4"

