[workspace]
authors = ["tdgfrost <100413067+tdgfrost@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "IrregularPongBenchmark"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"

[pypi-dependencies]
torch = ">=2.8.0, <3"
hydra-core = ">=1.3.2, <2"
omegaconf = ">=2.3.0, <3"
torchrl = ">=0.7.2, <0.10"
tensordict = ">=0.7.2, <0.10"
matplotlib = ">=3.10.5, <4"
torchvision = ">=0.23.0, <0.24"
tensorboard = ">=2.20.0, <3"
tqdm = ">=4.67.1, <5"
gymnasium = { version = "<1.0", extras = ["atari", "accept-rom-license"] }
