[workspace]
authors = ["tdgfrost <100413067+tdgfrost@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "IrregularPongBenchmark"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = "==3.11"

[pypi-dependencies]
tqdm = ">=4.67.1, <5"
matplotlib = ">=3.10.5, <4"
torch = ">=2.6.0, <3"

[feature.torchrl.pypi-dependencies]
hydra-core = ">=1.3.2, <2"
omegaconf = ">=2.3.0, <3"
torchrl = ">=0.7.2, <0.10"
tensordict = ">=0.7.2, <0.10"
torchvision = ">=0.23.0, <0.24"
tensorboard = ">=2.20.0, <3"
gymnasium = { version = "<1.0", extras = ["atari", "accept-rom-license"] }

[feature.pufferlib.tasks]
pufferlib = "uv pip install 'pufferlib[minigrid]' --no-build-isolation"

[feature.pufferlib.pypi-dependencies]
setuptools = ">=80.9.0, <81"
click = ">=8.2.1, <9"
requests = ">=2.32.5, <3"
stable-baselines3 = ">=2.7.0, <3"

[environments]
torchrl = ["torchrl"]
pufferlib = ["pufferlib"]

